### ISSUE TITLE
column identifiers for classification calibration

### ISSUE THREAD

**Issue by topepo** [tidymodels/tailor#46] opened 2024-09-19 17:44 UTC
For probability calibration, the `cal_estimate_*()` functions for _classification_ functions have an `estimate` argument that corresponds to the probability columns. The call for those functions in tailor is passing the hard class estimate column: 

https://github.com/tidymodels/tailor/blob/3385fbce71a7eb82bad53c8ced6c3463dc7c9a87/R/adjust-probability-calibration.R#L101

so that should probably (🙄) be `tailor$columns$probabilities`

Similarly, the call to `cal_apply()` should pass in data to the `pred_class` argument to that function:

https://github.com/tidymodels/tailor/blob/3385fbce71a7eb82bad53c8ced6c3463dc7c9a87/R/adjust-probability-calibration.R#L119

Specifically, it should most likely be `tailor$columns$estimate`. 

Finally, should we use `expr(data)` in `call2()` instead of embedding the data set in the call in `fit.probability_calibration()`?

**Comment by simonpcouch** [comment] 2024-09-19 19:47
Duplicate of #36. I'll close that issue in favor of this one since yours is more detailed.

**Comment by simonpcouch** [comment] 2024-09-19 21:00
Just added a commit to a branch referencing this issue. Your suggestion of what columns to pass is correct, though I'm having trouble interfacing with `probably:::tidyselect_cols()` correctly. With the noted commit, I see:

``` r
library(modeldata)
library(tailor)

# split example data
set.seed(1)
in_rows <- sample(c(TRUE, FALSE), nrow(two_class_example), replace = TRUE)
d_potato <- two_class_example[in_rows, ]
d_test <- two_class_example[!in_rows, ]

tlr <-
  tailor() %>%
  adjust_probability_calibration(method = "logistic")

tlr_fit <- fit(
  tlr,
  d_potato,
  outcome = c(truth),
  estimate = c(predicted),
  probabilities = c(Class1, Class2)
)

predict(tlr_fit, d_test)
#> Error in `purrr::map()`:
#> ℹ In index: 1.
#> Caused by error in `[<-.data.frame`:
#> ! anyNA() applied to non-(list or vector) of type 'symbol'
```

<sup>Created on 2024-09-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

(This is with the [aspirational tests](https://github.com/tidymodels/tailor/blob/3385fbce71a7eb82bad53c8ced6c3463dc7c9a87/tests/testthat/test-adjust-probability-calibration.R#L1) for `adjust_probability_calibration()`.)

It seems `apply_model_predict()` is trying to [subset data frame columns using symbols](https://github.com/tidymodels/probably/blob/28235ded71c7553abff95e8c021425ea0d0c6cfe/R/cal-apply-binary.R#L41-L42) when one passes `cal_estimate_logistic(estimate)` as a character, though using `all_of()` for a external vector selection triggers `all_of()`'s deprecation warning re: use outside of a selecting function.

**Closed** 2024-09-24 14:38 UTC
